#!/usr/bin/env bash

bismuthEnabled=$(grep "bismuthEnabled" ~/.config/kwinrc)


#echo "$bismuthEnabled"

if [[ $bismuthEnabled = bismuthEnabled=true ]]; then
  sed -i 's/bismuthEnabled=true/bismuthEnabled=false/g' ~/.config/kwinrc
  /home/frazer/Desktop/FreedomOS/freedomos-welcome-dev/usr/share/freedomos-welcome/restart-kwin.desktop && exit 1
else
  sed -i 's/bismuthEnabled=false/bismuthEnabled=true/g' ~/.config/kwinrc
  /home/frazer/Desktop/FreedomOS/freedomos-welcome-dev/usr/share/freedomos-welcome/restart-kwin.desktop && exit 1
fi
